# Generated by Django 5.0.1 on 2024-04-26 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket_money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gudian_first_name', models.CharField(max_length=100)),
                ('gudian_last_name', models.CharField(max_length=100)),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100)),
                ('pocket_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('admission_number', models.CharField(max_length=100)),
                ('total_fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pocket_money', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pocket_money')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.school')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.datetime(2024, 4, 26, 17, 36, 17, 92607))),
                ('student', models.ManyToManyField(to='mainapp.student')),
            ],
        ),
    ]
